services:
  - type: web
    name: landing-page-generator-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: MAX_DEPLOYS_PER_HOUR
        value: 10
      - key: NETLIFY_TOKEN
        sync: false  # You'll set this manually in Render dashboard 